version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  exclusions:
    rules:
      - path: '.*_test\.go'
        linters:
          - errcheck

linters-settings:
  govet:
    enable-all: false
  errcheck:
    check-type-assertions: false
    check-blank: false
  misspell:
    locale: US
